name: SSH Deploy

on:
  push:
    branches:
      - production
      
  workflow_dispatch:

jobs:
  deploy:
    name: Deployment on remote host
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH tunnel
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.PH_PRIVATEKEY }}

    - name: SSH command
      run: |
        echo "Starting deployment..."
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.PH_USER }}@${{ secrets.PH_HOST }} -p ${{ secrets.PH_PORT }} "cd /sites && git pull origin main"
        echo "Deployment completed."
