name: Deploy to Host

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: install node
      uses: actions/setup-node@v3
      
    - name: 📂 CD and PWD
      script: |
          ssh ${{ secrets.PH_USER }}@${{ secrets.PH_HOST }} -p ${{ secrets.PH_PORT }}
          touch toto.txt
          # cd /var/www
          # git pull origin production
          # npm install
          # npm run build
