name: Deploy to Host

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository latest code
      uses: actions/checkout@v4

    - name: install node 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: install SSH client
      run: sudo apt install -y openssh-client

    - name: tunnel to host
      run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.PH_HOST }} >> ~/.ssh/known_hosts
          
    - name: Deploy to VPS
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.PH_USER }}@${{ secrets.PH_HOST }} << EOF
          cd ${{ secrets.PH_PRIVATEPATH }}
          mkdir totoleBG
        EOF
       
