name: SSH Deploy

on:
  push:
    branches:
      - production
      
  workflow_dispatch:

jobs:
  deploy:
    name: Deployment on remote host
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH tunnel
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.PH_PRIVATEKEY }}

    - name: SSH commands
      uses: appleboy/ssh-action@master
      with:
        username: ${{ secrets.PH_USER }}
        host: ${{ secrets.PH_HOST }}
        port: ${{ secrets.PH_PORT }}
        key: ${{ secrets.PH_PRIVATEKEY }}
        script: |
          echo "Starting deployment..."
          cd ./sites
          git pull origin production
          echo "Ending deployment..."
