name: Deploy to Host

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install SSH client
      run: sudo apt-get install openssh-client -y

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.T_PRIVATEKEY }}

    - name: SSH into Host and check connection
      run: ssh -o StrictHostKeyChecking=no ${{ secrets.T.USER }}@${{ secrets.T_HOST }} -p ${{ secrets.T_PORT}} "echo Connected successfully"

