name: Deploy to Host

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: 📂 CD and PWD
      uses: appleboy/ssh-action@master
      with:
        script: |
          ssh ${{ secrets.PH_USER }}@${{ secrets.PH_HOST }} -p ${{ secrets.PH_PORT }}
          cd /var/www
          git pull origin production
          npm install
          npm run build

    
