

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.PH_PRIVATEKEY }}

    - name: SSH Command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PH_HOST }}
        username: ${{ secrets.PH_USER }}
        key: ${{ secrets.PH_PRIVATEKEY }}
        port: ${{ secrets.PH_PORT }}
        script: |
          mkdir totoBG
