name: Deploy to Host

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: SSH into Host and check connection
      run: |
        ssh ${{ secrets.PH_USER }}@${{ secrets.PH_HOST }} \
            -p ${{ secrets.PH_PORT }} \
            "echo Connected successfully"
